In [1]:
%%capture --no-stderr
%pip install --quiet -U vastdb

In [2]:
import pyarrow as pa
import vastdb
from ibis import _

ENDPOINT='http://172.200.204.1'
ACCESS_KEY='BR77TV2BSB1LQG4CH9QO'
SECRET_KEY='37tFv8Nd3tUFsQW7nyhFXLED0KUq7PW0Bj/cpjYg'

predicate=None # (_.key.isin([b'123']))

session = vastdb.connect(
    endpoint=ENDPOINT,
    access=ACCESS_KEY,
    secret=SECRET_KEY)

with session.transaction() as tx:
    bucket = tx.bucket('my-kafka')
    schema = bucket.schema('kafka_topics')
    table = schema.table('stock-settlement')

    # run `SELECT * FROM t WHERE predicate`
    result = table.select(predicate=predicate).read_all()
    # print(result)
    print(result.num_rows)

289316

In [3]:
import pandas as pd
pd.set_option('display.max_colwidth', 200)

In [4]:
result.to_pandas()

,key,value,timestamp_broker,timestamp_producer,headers
0,b'e20579bc-cd76-4ab9-9a5e-e87bfa9fe7f6',"b'{""transaction_id"": ""e20579bc-cd76-4ab9-9a5e-e87bfa9fe7f6"", ""trade_date"": ""2024-09-14T11:00:00"", ""settlement_date"": ""2024-09-16T11:00:00"", ""stock_symbol"": ""ONN"", ""quantity"": 9370, ""price"": 1625.8...",2025-04-19 06:31:59.422,2025-04-19 06:31:59.375,[]
1,b'e9c6c4ef-200a-4c9b-8c2c-7df77ef27107',"b'{""transaction_id"": ""e9c6c4ef-200a-4c9b-8c2c-7df77ef27107"", ""trade_date"": ""2024-05-18T11:00:00"", ""settlement_date"": ""2024-05-20T11:00:00"", ""stock_symbol"": ""WUJ"", ""quantity"": 3761, ""price"": 3879.5...",2025-04-19 06:31:59.422,2025-04-19 06:31:59.384,[]
2,b'badbb6a3-9db8-4486-a511-a69266c1b7dc',"b'{""transaction_id"": ""badbb6a3-9db8-4486-a511-a69266c1b7dc"", ""trade_date"": ""2025-01-22T10:00:00"", ""settlement_date"": ""2025-01-24T10:00:00"", ""stock_symbol"": ""YHW"", ""quantity"": 7257, ""price"": 2969.1...",2025-04-19 06:31:59.422,2025-04-19 06:31:59.385,[]
3,b'6852244c-b7c8-4437-9dba-76e25dece5ea',"b'{""transaction_id"": ""6852244c-b7c8-4437-9dba-76e25dece5ea"", ""trade_date"": ""2024-07-15T06:00:00"", ""settlement_date"": ""2024-07-18T06:00:00"", ""stock_symbol"": ""ZSB"", ""quantity"": 5934, ""price"": 3399.1...",2025-04-19 06:31:59.422,2025-04-19 06:31:59.385,[]
4,b'45214454-fa3a-445d-b2c9-02f9a5a503b7',"b'{""transaction_id"": ""45214454-fa3a-445d-b2c9-02f9a5a503b7"", ""trade_date"": ""2024-12-21T16:00:00"", ""settlement_date"": ""2024-12-22T16:00:00"", ""stock_symbol"": ""VWQ"", ""quantity"": 2111, ""price"": 1893.9...",2025-04-19 06:31:59.422,2025-04-19 06:31:59.385,[]
...,...,...,...,...,...
289311,b'fe40907d-386d-4774-88ba-c6d6a228fdff',"b'{""transaction_id"": ""fe40907d-386d-4774-88ba-c6d6a228fdff"", ""trade_date"": ""2025-01-08T07:00:00"", ""settlement_date"": ""2025-01-10T07:00:00"", ""stock_symbol"": ""SLG"", ""quantity"": 4740, ""price"": 3493.1...",2025-04-19 06:35:05.365,2025-04-19 06:35:04.546,[]
289312,b'f8b97faa-22ae-4ac5-863b-4e689d43392a',"b'{""transaction_id"": ""f8b97faa-22ae-4ac5-863b-4e689d43392a"", ""trade_date"": ""2024-05-06T11:00:00"", ""settlement_date"": ""2024-05-06T11:00:00"", ""stock_symbol"": ""XYZ"", ""quantity"": 5345, ""price"": 23617....",2025-04-19 06:35:05.365,2025-04-19 06:35:04.546,[]
289313,b'f00c4fcc-0f85-491f-8cf9-40b9932e2684',"b'{""transaction_id"": ""f00c4fcc-0f85-491f-8cf9-40b9932e2684"", ""trade_date"": ""2024-09-15T06:00:00"", ""settlement_date"": ""2024-09-16T06:00:00"", ""stock_symbol"": ""NRX"", ""quantity"": 2135, ""price"": 849.15...",2025-04-19 06:35:05.365,2025-04-19 06:35:04.546,[]
289314,b'26bb812a-a943-42b4-97e2-f73e2e4aa8fc',"b'{""transaction_id"": ""26bb812a-a943-42b4-97e2-f73e2e4aa8fc"", ""trade_date"": ""2024-08-26T06:00:00"", ""settlement_date"": ""2024-08-28T06:00:00"", ""stock_symbol"": ""KZW"", ""quantity"": 8955, ""price"": 4052.2...",2025-04-19 06:35:05.365,2025-04-19 06:35:04.546,[]
289315,b'430e4337-e4cb-4ac0-af0a-8d1f91e15443',"b'{""transaction_id"": ""430e4337-e4cb-4ac0-af0a-8d1f91e15443"", ""trade_date"": ""2024-08-29T11:00:00"", ""settlement_date"": ""2024-08-31T11:00:00"", ""stock_symbol"": ""IKJ"", ""quantity"": 9965, ""price"": 1759.4...",2025-04-19 06:35:05.365,2025-04-19 06:35:04.546,[]