# Audit Log queries via Trino Connection

Also see: 
- https://grafana.com/grafana/dashboards/22292-vast-audit-dashboard/

In [1]:
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [2]:
%load_ext sql

In [3]:
%sql trino://admin@${DOCKER_HOST_OR_IP}:8443/vast  --connection_arguments '{"http_scheme":"https", "verify": false}'

Connecting to 'trino://admin@10.143.11.241:8443/vast'

In [33]:
%%sql

SELECT
    *
FROM 
    "vast-audit-log-bucket|vast_audit_log_schema".vast_audit_log_table
WHERE
    view_path like '/csnow%' 
    and protocol <> 'NDB'
ORDER BY
    time DESC
LIMIT 10

Running query in 'trino://admin@10.143.11.241:8443/vast'

,cluster_name,cnode_name,time,client_ip,cluster_vip,tenant,protocol,rpc_type,path,view_path,...,smb_create_action,smb_create_option,smb_create_disposition,smb_delete_on_close,smb_info_type,smb_info_class,smb_rename_struct,num_ops,num_bytes,time_str
0,selab-var-204,cnode-3-14,2024-12-09 16:46:00.743450,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2015...,/csnow-bucket,...,None,None,None,None,None,None,None,1,11250,2024-12-09T16:46:00.743Z
1,selab-var-204,cnode-3-14,2024-12-09 16:46:00.742352,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2016...,/csnow-bucket,...,None,None,None,None,None,None,None,1,10957,2024-12-09T16:46:00.742Z
2,selab-var-204,cnode-3-14,2024-12-09 16:46:00.739602,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2015...,/csnow-bucket,...,None,None,None,None,None,None,None,1,12562,2024-12-09T16:46:00.739Z
3,selab-var-204,cnode-3-14,2024-12-09 16:46:00.738498,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2016...,/csnow-bucket,...,None,None,None,None,None,None,None,1,12861,2024-12-09T16:46:00.738Z
4,selab-var-204,cnode-3-14,2024-12-09 16:46:00.738013,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2010...,/csnow-bucket,...,None,None,None,None,None,None,None,1,10405,2024-12-09T16:46:00.738Z
5,selab-var-204,cnode-3-14,2024-12-09 16:46:00.737418,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2010...,/csnow-bucket,...,None,None,None,None,None,None,None,1,49216,2024-12-09T16:46:00.737Z
6,selab-var-204,cnode-3-14,2024-12-09 16:46:00.737001,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2010...,/csnow-bucket,...,None,None,None,None,None,None,None,1,49216,2024-12-09T16:46:00.737Z
7,selab-var-204,cnode-3-14,2024-12-09 16:46:00.736670,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2009...,/csnow-bucket,...,None,None,None,None,None,None,None,1,49216,2024-12-09T16:46:00.736Z
8,selab-var-204,cnode-3-14,2024-12-09 16:46:00.736654,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2010...,/csnow-bucket,...,None,None,None,None,None,None,None,1,49216,2024-12-09T16:46:00.736Z
9,selab-var-204,cnode-3-14,2024-12-09 16:46:00.736553,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/nyt/yellow_tripdata_2010...,/csnow-bucket,...,None,None,None,None,None,None,None,1,49216,2024-12-09T16:46:00.736Z

## Using a Dataframe

Sometime we just need a pandas dataframe

In [34]:
%config SqlMagic.autopandas = True
df = %sql SELECT * FROM "vast-audit-log-bucket|vast_audit_log_schema".vast_audit_log_table
df

Running query in 'trino://admin@10.143.11.241:8443/vast'

,cluster_name,cnode_name,time,client_ip,cluster_vip,tenant,protocol,rpc_type,path,view_path,...,smb_create_action,smb_create_option,smb_create_disposition,smb_delete_on_close,smb_info_type,smb_info_class,smb_rename_struct,num_ops,num_bytes,time_str
0,selab-var-204,cnode-3-14,2024-12-09 10:36:21.180570,172.200.12.241,172.200.204.2,default,S3,PUT_OBJECT,(path: '/csnow-bucket/iceberg/twitter_data-24c...,/csnow-bucket,...,None,None,None,None,None,None,None,1,0,2024-12-09T10:36:21.180Z
1,selab-var-204,cnode-3-14,2024-12-09 10:36:21.235536,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/iceberg/twitter_data-24c...,/csnow-bucket,...,None,None,None,None,None,None,None,1,4125,2024-12-09T10:36:21.235Z
2,selab-var-204,cnode-3-14,2024-12-09 10:36:21.328924,172.200.12.241,172.200.204.2,default,S3,PUT_OBJECT,(path: '/csnow-bucket/iceberg/twitter_data-24c...,/csnow-bucket,...,None,None,None,None,None,None,None,1,0,2024-12-09T10:36:21.328Z
3,selab-var-204,cnode-3-14,2024-12-09 10:36:21.975770,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/iceberg/twitter_data-24c...,/csnow-bucket,...,None,None,None,None,None,None,None,1,2044,2024-12-09T10:36:21.975Z
4,selab-var-204,cnode-3-14,2024-12-09 10:36:23.221401,172.200.12.241,172.200.204.2,default,S3,GET_OBJECT,(path: '/csnow-bucket/iceberg/twitter_data-24c...,/csnow-bucket,...,None,None,None,None,None,None,None,1,2044,2024-12-09T10:36:23.221Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29253,selab-var-204,cnode-3-15,2024-12-09 17:14:16.067721,172.16.3.13,172.16.4.204,default,NDB,LIST_COLUMNS,(path: '/vast-big-catalog-bucket/vast_big_cata...,/vast-big-catalog-bucket,...,None,None,None,None,None,None,None,1,0,2024-12-09T17:14:16.067Z
29254,selab-var-204,cnode-3-15,2024-12-09 17:14:26.583642,172.16.3.13,172.16.4.204,default,NDB,LIST_COLUMNS,(path: '/vast-big-catalog-bucket/vast_big_cata...,/vast-big-catalog-bucket,...,None,None,None,None,None,None,None,1,4360,2024-12-09T17:14:26.583Z
29255,selab-var-204,cnode-3-15,2024-12-09 17:14:26.586637,172.16.3.13,172.16.4.204,default,NDB,LIST_COLUMNS,(path: '/vast-big-catalog-bucket/vast_big_cata...,/vast-big-catalog-bucket,...,None,None,None,None,None,None,None,1,0,2024-12-09T17:14:26.586Z
29256,selab-var-204,cnode-3-15,2024-12-09 17:14:36.600281,172.16.3.13,172.16.4.204,default,NDB,LIST_COLUMNS,(path: '/vast-big-catalog-bucket/vast_big_cata...,/vast-big-catalog-bucket,...,None,None,None,None,None,None,None,1,4360,2024-12-09T17:14:36.600Z
29257,selab-var-204,cnode-3-15,2024-12-09 17:14:36.604201,172.16.3.13,172.16.4.204,default,NDB,LIST_COLUMNS,(path: '/vast-big-catalog-bucket/vast_big_cata...,/vast-big-catalog-bucket,...,None,None,None,None,None,None,None,1,0,2024-12-09T17:14:36.604Z